# Copyright (C) 2020  Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions 
# and other software and tools, and any partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License 
# Subscription Agreement, the Intel Quartus Prime License Agreement,
# the Intel FPGA IP License Agreement, or other applicable license
# agreement, including, without limitation, that your use is for
# the sole purpose of programming logic devices manufactured by
# Intel and sold by Intel or its authorized distributors.  Please
# refer to the applicable agreement for further details, at
# https://fpgasoftware.intel.com/eula.


# ***************************************************************************
# ***************************************************************************
# 
# File:		C:/Users/ZaKaye/Desktop/Pixiv/MEng Study 2021 Fall/FPGA/lab1/lab1_dump_all_vcd_nodes.tcl
# 
# Description:	Script for ModelSim-Altera (Verilog) VCD File Dumping
# 		This script is used to direct ModelSim-Altera (Verilog) to dump
# 		all nodes in the design to a VCD output file
# 
# Usages:	C:/Users/ZaKaye/Desktop/Pixiv/MEng Study 2021 Fall/FPGA/lab1/lab1_dump_all_vcd_nodes.tcl
# 
# Generated by:	Quartus Prime
# 		Version 20.1.1 Build 720 11/11/2020 SJ Standard Edition
# 
# Date:		Thu Oct 07 19:59:51 2021
# 
# Design:	lab1
# 
# ***************************************************************************
# ***************************************************************************

# ----------------------------------------------------------------
#
proc add_vcd_signals { hierarchy vcd_filename } {
#
# Description:	This function directs ModelSim-Altera (Verilog) to print out the
#		appropriate VCD signals, with the hierarchy level
#		prepended to each signal name
#
# ----------------------------------------------------------------

   catch { vcd add "$hierarchy/Mult4_ao_res\[0\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[1\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[2\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[3\]" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a26" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a27" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a28" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a29" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a30" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a31" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a32" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a33" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a34" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a35" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a36" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a37" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a38" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a39" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a40" }
   catch { vcd add "$hierarchy/Mult4_aMult0_a41" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[4\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[5\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[6\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[7\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[8\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[9\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[10\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[11\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[12\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[13\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[14\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[15\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[16\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[17\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[18\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[19\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[20\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[21\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[22\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[23\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[24\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[25\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[26\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[27\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[28\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[29\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[30\]" }
   catch { vcd add "$hierarchy/Mult4_ao_res\[31\]" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a1_sumout" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a2" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a5_sumout" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a6" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a9_sumout" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a10" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a13_sumout" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a14" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a17_sumout" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a18" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a21_sumout" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a22" }
   catch { vcd add "$hierarchy/Addr4_aAdd0_a25_sumout" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[0\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[1\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[2\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[3\]" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a26" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a27" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a28" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a29" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a30" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a31" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a32" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a33" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a34" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a35" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a36" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a37" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a38" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a39" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a40" }
   catch { vcd add "$hierarchy/Mult3_aMult0_a41" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[4\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[5\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[6\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[7\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[8\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[9\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[10\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[11\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[12\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[13\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[14\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[15\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[16\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[17\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[18\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[19\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[20\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[21\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[22\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[23\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[24\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[25\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[26\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[27\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[28\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[29\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[30\]" }
   catch { vcd add "$hierarchy/Mult3_ao_res\[31\]" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a1_sumout" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a2" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a5_sumout" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a6" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a9_sumout" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a10" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a13_sumout" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a14" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a17_sumout" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a18" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a21_sumout" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a22" }
   catch { vcd add "$hierarchy/Addr3_aAdd0_a25_sumout" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[0\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[1\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[2\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[3\]" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a26" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a27" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a28" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a29" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a30" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a31" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a32" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a33" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a34" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a35" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a36" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a37" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a38" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a39" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a40" }
   catch { vcd add "$hierarchy/Mult2_aMult0_a41" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[4\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[5\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[6\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[7\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[8\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[9\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[10\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[11\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[12\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[13\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[14\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[15\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[16\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[17\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[18\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[19\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[20\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[21\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[22\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[23\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[24\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[25\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[26\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[27\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[28\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[29\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[30\]" }
   catch { vcd add "$hierarchy/Mult2_ao_res\[31\]" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a1_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a2" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a5_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a6" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a9_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a10" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a13_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a14" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a17_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a18" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a21_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a22" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a25_sumout" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a26" }
   catch { vcd add "$hierarchy/Addr2_aAdd0_a29_sumout" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[0\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[1\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[2\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[3\]" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a26" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a27" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a28" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a29" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a30" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a31" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a32" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a33" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a34" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a35" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a36" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a37" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a38" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a39" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a40" }
   catch { vcd add "$hierarchy/Mult1_aMult0_a41" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[4\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[5\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[6\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[7\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[8\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[9\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[10\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[11\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[12\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[13\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[14\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[15\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[16\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[17\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[18\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[19\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[20\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[21\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[22\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[23\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[24\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[25\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[26\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[27\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[28\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[29\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[30\]" }
   catch { vcd add "$hierarchy/Mult1_ao_res\[31\]" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a1_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a2" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a5_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a6" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a9_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a10" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a13_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a14" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a17_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a18" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a21_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a22" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a25_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a26" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a29_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a30" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a33_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a34" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a37_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a38" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a41_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a42" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a45_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a46" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a49_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a50" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a53_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a54" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a57_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a58" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a61_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a62" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a65_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a66" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a69_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a70" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a73_sumout" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a74" }
   catch { vcd add "$hierarchy/Addr1_aAdd0_a77_sumout" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a453" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a454" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a455" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a456" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a457" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a458" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a459" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a460" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a461" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a462" }
   catch { vcd add "$hierarchy/Mult0_aMult0_a463" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[11\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[12\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[13\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[14\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[15\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[16\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[17\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[18\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[19\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[20\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[21\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[22\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[23\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[24\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[25\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[26\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[27\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[28\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[29\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[30\]" }
   catch { vcd add "$hierarchy/Addr0_ao_res\[31\]" }
   catch { vcd add "$hierarchy/valid_Q2_aq" }
   catch { vcd add "$hierarchy/o_valid_a0_combout" }
   catch { vcd add "$hierarchy/y_Q\[0\]" }
   catch { vcd add "$hierarchy/y_Q\[1\]" }
   catch { vcd add "$hierarchy/y_Q\[2\]" }
   catch { vcd add "$hierarchy/y_Q\[3\]" }
   catch { vcd add "$hierarchy/y_Q\[4\]" }
   catch { vcd add "$hierarchy/y_Q\[5\]" }
   catch { vcd add "$hierarchy/y_Q\[6\]" }
   catch { vcd add "$hierarchy/y_Q\[7\]" }
   catch { vcd add "$hierarchy/y_Q\[8\]" }
   catch { vcd add "$hierarchy/y_Q\[9\]" }
   catch { vcd add "$hierarchy/y_Q\[10\]" }
   catch { vcd add "$hierarchy/y_Q\[11\]" }
   catch { vcd add "$hierarchy/y_Q\[12\]" }
   catch { vcd add "$hierarchy/y_Q\[13\]" }
   catch { vcd add "$hierarchy/y_Q\[14\]" }
   catch { vcd add "$hierarchy/y_Q\[15\]" }
   catch { vcd add "$hierarchy/y_Q\[16\]" }
   catch { vcd add "$hierarchy/y_Q\[17\]" }
   catch { vcd add "$hierarchy/y_Q\[18\]" }
   catch { vcd add "$hierarchy/y_Q\[19\]" }
   catch { vcd add "$hierarchy/y_Q\[20\]" }
   catch { vcd add "$hierarchy/y_Q\[21\]" }
   catch { vcd add "$hierarchy/y_Q\[22\]" }
   catch { vcd add "$hierarchy/y_Q\[23\]" }
   catch { vcd add "$hierarchy/y_Q\[24\]" }
   catch { vcd add "$hierarchy/y_Q\[25\]" }
   catch { vcd add "$hierarchy/y_Q\[26\]" }
   catch { vcd add "$hierarchy/y_Q\[27\]" }
   catch { vcd add "$hierarchy/y_Q\[28\]" }
   catch { vcd add "$hierarchy/y_Q\[29\]" }
   catch { vcd add "$hierarchy/y_Q\[30\]" }
   catch { vcd add "$hierarchy/y_Q\[31\]" }
   catch { vcd add "$hierarchy/valid_Q1_aq" }
   catch { vcd add "$hierarchy/clk_ainput_o" }
   catch { vcd add "$hierarchy/clk_ainputCLKENA0_outclk" }
   catch { vcd add "$hierarchy/o_valid_aoutput2_o" }
   catch { vcd add "$hierarchy/o_ready_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a0_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a1_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a2_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a3_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a4_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a5_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a6_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a7_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a8_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a9_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a10_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a11_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a12_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a13_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a14_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a15_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a16_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a17_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a18_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a19_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a20_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a21_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a22_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a23_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a24_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a25_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a26_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a27_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a28_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a29_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a30_a_aoutput2_o" }
   catch { vcd add "$hierarchy/o_y_a31_a_aoutput2_o" }
   catch { vcd add "$hierarchy/i_ready_ainput5" }
   catch { vcd add "$hierarchy/reset_ainput5" }
   catch { vcd add "$hierarchy/i_valid_ainput5" }
   catch { vcd add "$hierarchy/i_x_a0_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a1_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a2_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a3_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a4_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a5_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a6_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a7_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a8_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a9_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a10_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a11_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a12_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a13_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a14_a_ainput5" }
   catch { vcd add "$hierarchy/i_x_a15_a_ainput5" }
}

# ----------------------------------------------------------------
#
proc main { argv } {
#
# Description:	Main entry point to script.  Iterate over all
#		hierarchy levels specified, and direct ModelSim-Altera (Verilog)
#		to print the relevant signals under each level
#
# ----------------------------------------------------------------

   set vcd_filename "lab1.vcd"
   set hierarchy "dut"

   vcd file "$vcd_filename"
   vcd on

   add_vcd_signals $hierarchy $vcd_filename
}

main $argv
